name: Notion → PostgreSQL Sync

on:
  schedule:
    - cron: '0 0 * * *'        # every night at midnight UTC
  workflow_dispatch:

jobs:
  sync:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repo
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run Notion → Postgres sync
        env:
          NOTION_TOKEN:       ${{ secrets.NOTION_TOKEN }}
          NOTION_DATABASE_ID: ${{ secrets.NOTION_DATABASE_ID }}
          PGHOST:             ${{ secrets.SUPABASE_HOST }}
          PGPORT:             ${{ secrets.SUPABASE_PORT }}
          PGUSER:             ${{ secrets.DB_USER }}
          PGPASSWORD:         ${{ secrets.DB_PASSWORD }}
          PGDATABASE:         ${{ secrets.DB_NAME }}
        run: python notion_sync_tasks.py
